# Feature engineering

Load data set

In [1]:
import pandas as pd
import numpy as np
import sklearn
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import QuantileTransformer
from sklearn.ensemble import RandomForestClassifier

In [2]:
df_train_no_nan=pd.read_csv('df_train_no_Nan.csv')
df_train_balanced=pd.read_csv('df_train_balanced.csv')

In [3]:
df_test=pd.read_csv('df_test.csv')

In [4]:
df_train_balanced

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,401887,0,Cash loans,F,N,N,1,112500.0,273636.0,27193.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,368548,0,Cash loans,F,N,Y,0,135000.0,375322.5,26248.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,358815,0,Revolving loans,F,Y,Y,0,166500.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,298219,0,Cash loans,M,N,Y,2,675000.0,1288350.0,41692.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
4,180560,0,Cash loans,F,N,Y,0,54000.0,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7523,456108,1,Cash loans,F,N,Y,1,135000.0,457834.5,33444.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
7524,456140,1,Cash loans,F,Y,Y,1,261000.0,711454.5,47673.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
7525,456176,1,Cash loans,M,N,Y,0,171000.0,1436850.0,42142.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
7526,456186,1,Cash loans,M,N,N,1,207000.0,450000.0,32746.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
7527,456233,1,Cash loans,F,N,Y,0,225000.0,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0

## Normalize the rest numerical column

select all numerical column

In [6]:
df_numerical_nan=df_train_no_nan.select_dtypes(['float','int'])
df_numerical_balanced=df_train_balanced.select_dtypes(['float','int'])
df_numerical_test=df_test.select_dtypes(['float','int'])

In [7]:
qt = QuantileTransformer(output_distribution='normal')

In [8]:
ls_all_nan=df_numerical_nan.columns.tolist()
ls_all_balanced=df_numerical_balanced.columns.tolist()
ls_test=df_numerical_test.columns.tolist()

Remove the target value and process

In [9]:
del ls_all_nan[1]
del ls_all_balanced[1]

In [10]:
for k in ls_all_nan:
    df_train_no_nan[k] = qt.fit_transform(df_train_no_nan[[k]].values.reshape(-1,1))

In [11]:
for k in ls_all_balanced:
    df_train_balanced[k] = qt.fit_transform(df_train_balanced[[k]].values.reshape(-1,1))

In [12]:
for k in ls_test:
    df_test[k] = qt.fit_transform(df_test[[k]].values.reshape(-1,1))

In [13]:
df_train_balanced

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,1.029667,0,Cash loans,F,N,N,0.713599,-0.884593,-0.778225,0.079120,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-0.320290
1,0.685680,0,Cash loans,F,N,Y,-5.199338,-0.434861,-0.447305,-0.017911,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,0.697507
2,0.602888,0,Revolving loans,F,Y,Y,-5.199338,0.038901,-0.539431,-0.791884,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338
3,0.146620,0,Cash loans,M,N,Y,1.550085,2.542349,1.453280,1.025123,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-0.320290
4,-0.747742,0,Cash loans,F,N,Y,-5.199338,-2.651732,-2.478881,-2.571132,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,0.697507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7523,3.322190,1,Cash loans,F,N,Y,0.713599,-0.434861,-0.205941,0.527204,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,0.231641
7524,3.403824,1,Cash loans,F,Y,Y,0.713599,0.973449,0.427563,1.328620,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,1.184447,-5.199338,-0.320290
7525,3.535327,1,Cash loans,M,N,Y,-5.199338,0.061513,1.733071,1.048748,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,1.157061,0.231641
7526,3.585976,1,Cash loans,M,N,N,0.713599,0.535083,-0.274391,0.486258,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,0.231641
7527,5.199338,1,Cash loans,F,N,Y,-5.199338,0.703922,-0.040157,-0.267291,...,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,-5.199338,1.157061,0.231641

## One encode categoriacl data

We use one-hot encoding to convert categorical variables into binary variables

In [14]:
categorical_variables_nan=df_train_no_nan.select_dtypes(exclude=['int','float'])
categorical_variables_balanced=df_train_balanced.select_dtypes(exclude=['int','float'])
categorical_variables_test=df_test.select_dtypes(exclude=['int','float'])

In [15]:
ls_nan=categorical_variables_nan.columns.tolist()
ls_balanced=categorical_variables_balanced.columns.tolist()
ls_test=categorical_variables_test.columns.tolist()

In [16]:
df_dummies_nan=pd.get_dummies(data=df_train_no_nan, columns=ls_nan)
df_dummies_nan

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,-5.199338,1,-5.199338,0.384375,-0.391347,-0.169372,-0.417002,-0.153660,1.666158,0.862544,...,0,0,0,0,0,0,1,0,1,0
1,-3.718161,0,0.723343,0.628724,0.741388,0.146752,0.567211,-0.332198,0.181194,-0.528889,...,0,0,0,0,0,1,0,0,1,0
2,-3.644828,0,-5.199338,-0.922330,-1.634747,-2.033104,-1.509656,1.407905,-0.668348,-1.653277,...,0,0,0,0,0,0,1,0,1,0
3,-3.597666,0,0.723343,1.951050,-0.160010,0.403015,-0.176553,0.119468,0.960852,-0.935297,...,0,0,0,0,0,1,0,0,1,0
4,-3.566906,0,1.550085,-0.478025,-1.014571,-1.213405,-0.746351,0.522099,0.912833,0.750178,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24614,3.552239,0,-5.199338,-0.148584,-1.077042,-1.592952,-1.467860,0.656486,-0.018820,0.117951,...,0,0,0,0,0,0,1,0,1,0
24615,3.580868,0,-5.199338,-1.700222,-0.961429,-0.957454,-0.997920,-1.798663,-1.170758,-0.534756,...,0,0,0,0,0,0,1,0,1,0
24616,3.624279,0,-5.199338,0.989697,1.907594,1.155458,1.857689,0.425228,-0.556116,-0.525919,...,0,0,0,0,0,0,1,0,1,0
24617,3.739484,0,-5.199338,-0.478025,0.418371,0.226857,0.506348,-0.153660,-1.173024,0.708253,...,0,0,0,0,0,0,1,0,1,0
24618,5.199338,0,1.550085,0.026650,0.317650,-0.634851,0.208505,1.407905,0.227923,-0.106841,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_dummies_balanced=pd.get_dummies(data=df_train_balanced, columns=ls_balanced)
df_dummies_balanced

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,1.029667,0,0.713599,-0.884593,-0.778225,0.079120,-0.728240,-0.006273,-0.197553,-1.727902,...,0,0,0,0,0,1,0,0,1,0
1,0.685680,0,-5.199338,-0.434861,-0.447305,-0.017911,-0.451469,-1.212751,-1.580542,0.215297,...,0,0,0,0,0,1,0,0,1,0
2,0.602888,0,-5.199338,0.038901,-0.539431,-0.791884,-0.423855,-0.797044,0.627196,0.961070,...,0,0,0,0,0,0,1,0,1,0
3,0.146620,0,1.550085,2.542349,1.453280,1.025123,1.362078,5.199338,-0.868398,-0.333619,...,0,0,0,0,0,1,0,0,1,0
4,-0.747742,0,-5.199338,-2.651732,-2.478881,-2.571132,-2.511791,-0.195700,0.165095,0.222201,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7523,3.322190,1,0.713599,-0.434861,-0.205941,0.527204,-0.336255,0.167640,0.488133,-0.217147,...,0,0,0,0,0,0,1,0,1,0
7524,3.403824,1,0.713599,0.973449,0.427563,1.328620,0.374936,-0.090452,0.786968,-0.079624,...,0,0,0,0,0,1,0,0,1,0
7525,3.535327,1,-5.199338,0.061513,1.733071,1.048748,1.362078,1.123415,0.834145,-0.705812,...,0,0,0,0,0,0,1,0,1,0
7526,3.585976,1,0.713599,0.535083,-0.274391,0.486258,-0.103057,0.071571,1.397964,-0.689510,...,0,0,0,0,0,0,1,0,1,0
7527,5.199338,1,-5.199338,0.703922,-0.040157,-0.267291,-0.103057,-0.479432,-0.474776,1.313816,...,0,0,0,0,0,0,1,0,0,1

In [18]:
df_dummies_test=pd.get_dummies(data=df_test, columns=ls_test)
df_dummies_test

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,-5.199338,1.579968,1.186981,1.811457,1.023003,1.873053,0.509202,0.209327,0.029800,0.584551,...,0,0,0,0,0,1,0,0,1,0
1,-3.952911,-5.199338,0.901416,1.080589,0.384455,0.951518,0.432104,-0.930962,-2.413129,-0.373473,...,0,1,0,0,0,0,0,0,1,0
2,-3.517482,-5.199338,0.015055,-0.556927,-0.517790,-0.842694,0.979511,0.320742,0.598915,-0.296683,...,0,0,0,0,0,0,1,0,1,0
3,-3.454423,0.746351,0.533636,-0.188033,-0.341493,-0.211070,0.432104,1.060909,0.020689,2.104112,...,0,0,0,0,0,1,0,0,1,0
4,-3.400432,-5.199338,-1.346386,-0.999986,-0.692715,-0.842694,-1.264066,1.223112,-0.333524,-0.131798,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8398,3.229139,-5.199338,0.533636,-0.663276,0.288000,-0.842694,-1.264066,0.831209,-0.943986,-0.156744,...,0,0,0,0,0,1,0,0,1,0
8399,3.234652,-5.199338,-1.068522,-1.418119,-0.945616,-1.467860,-0.593940,0.744694,2.702784,0.737605,...,0,0,0,0,0,0,1,0,1,0
8400,3.339828,0.746351,-1.068522,0.605701,0.419115,0.444534,-0.729877,1.156164,-0.028916,0.344582,...,0,0,0,0,0,1,0,0,1,0
8401,4.110136,0.746351,-1.068522,0.135645,-0.844790,-0.139710,0.043924,-0.258665,-0.119468,-0.164297,...,0,0,0,0,0,0,1,0,1,0
8402,5.199338,0.746351,0.015055,-1.460531,-1.075207,-1.467860,-0.299230,-0.269742,-1.409668,0.671732,...,0,0,0,0,0,1,0,0,1,0

## Saving new dataset

Save new and process dataset

In [19]:
df_dummies_test.to_csv('df_clean_test.csv',index=False)

# Saving the Dataframes into CSV files for future use
df_dummies_nan.to_csv('df_dummies_nan.csv')

In [20]:
df_dummies_balanced.to_csv('df_balanced.csv',index=False)

In [21]:
df_dummies_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8403 entries, 0 to 8402
Columns: 213 entries, SK_ID_CURR to EMERGENCYSTATE_MODE_Yes
dtypes: float64(82), uint8(131)
memory usage: 6.3 MB

In [22]:
df_dummies_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7528 entries, 0 to 7527
Columns: 213 entries, SK_ID_CURR to EMERGENCYSTATE_MODE_Yes
dtypes: float64(82), int64(1), uint8(130)
memory usage: 5.7 MB